; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=GitPic
AppVersion=1.0.0
DefaultDirName={pf}/GitPic
OutputDir=setup
OutputBaseFilename=GitPic_setup
SolidCompression=yes
SetupIconFile=./gitpic_128x128.ico

[Files]
Source: "output/*"; DestDir: {app}; Flags: ignoreversion recursesubdirs

[Icons]
Name: "{group}\icon"; Filename: "./gitpic_128x128.ico"
